# -*- coding: utf-8 -*-
"""newegg(clean)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x1fQE3lA0_aiXuZEGeeXgtXD0ktnm2FH

# Laptop Price Analysis – Newegg

In this project, laptop data from Newegg was cleaned and analyzed to understand
how RAM and SSD configurations affect laptop prices.

پاکسازی داده(Data Cleaning)

## Data Cleaning

In this section, we clean the raw dataset by:
- Removing empty rows
- Fixing invalid prices
- Standardizing RAM and SSD formats

فراخوانی فایل Excel(Import)
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
try:
    df = pd.read_excel('newegg.xlsx')
except Exception as e:
    print(f"cant read file {e}")
except FileNotFoundError:
    print("cant find the file")

"""(Check Data)بررسی اولیه"""

df.head(3)

df.info()

df.describe(include=object)

df.shape
df.sample(3)

df.tail(2)

"""(Type Of Data)نوع داده ها"""

df["Brand"] = df["Brand"].astype(str)
df["Color"] = df["Color"].astype(str)
df["Price"] = df["Price"].astype(str).str.replace(",", "")
df["Price"] = pd.to_numeric(df["Price"], errors="coerce")
print(df.dtypes)

"""(NaN)مقادیر خالی"""

df.isna().sum()

df = df.dropna(thresh=df.shape[1]-3, axis=0)
df = df.reset_index(drop=True)
print(df.head(2))
print(len(df))

df["Brand"] = df["Brand"].fillna("unkonw")
df["CPU"] = df["CPU"].ffill()
df["Memory"] = df["Memory"].bfill()
df["SSD"] = df["SSD"].ffill()
df["External GPU"] = df["External GPU"].fillna("Dont have External GPU(OnBord)")

df["Price"].min(), df["Price"].max()
df = df[df["Price"].between(120, 9000)]
print(len(df))

"""مرتب سازی براساس قیمت"""

df.sort_values(by="Price", ascending=False, inplace=True)
df.reset_index(drop=True, inplace=True)
print(df.head(3))

"""استخراج ویژگی(Feature Extraction)

## Feature Extraction

RAM and SSD values are extracted from text fields and converted into numerical
values for analysis.

استخراج مقدار عددی RAM و SSD(extract number oh RAM and SSD)
"""

ram = df["Memory"].str.extract(r"(\d+)\s*GB", expand=True)
df["RAM_GB"] = ram[0].astype(float)
ssd = df["SSD"].str.extract(r"(\d+)\s*(GB|TB)", expand=True)
value = ssd[0].astype(float)
key = ssd[1]
df["SSD_GB"] = value
df.loc[key == "TB", "SSD_GB"] *= 1024
df.head(3)

df = df.dropna(subset=["SSD_GB"])
df["RAM_GB"] = df["RAM_GB"].fillna(8)
print(len(df))

"""(Final Check)وضعیت نهایی"""

df.head(3)

df.info()

df.describe(include='all')

print(f"Number of rows: {len(df)}")

df.to_excel("output.xlsx")

"""(Analysis & Reports)گزارش ها

## Analysis & Reports

This section explores pricing patterns based on hardware configurations.
"""

print(f"Number of Laptops: {len(df)}")
print(f"Number of Brands: {len(df['Brand'].unique())}")
print(f"Number of Colors: {len(df['Color'].unique())}")
print(f"Highest Price: {df["Price"].max()}")
print(f"Lowest Price: {df["Price"].min()}")
print(f"Mean Price: {df["Price"].mean().round(2)}")

price_catagory = pd.cut(df["Price"], bins=[100, 500, 1200, 3957.99], labels=["Low", "Medain", "Hight"])
hight_percent = (price_catagory == "Hight").sum() / len(df) * 100
print(f"Hight_percent: {hight_percent.round(2)} %")
medain_percent = (price_catagory == "Medain").sum() / len(df) * 100
print(f"Medain percent: {medain_percent.round(2)} %")
low_percent = (price_catagory == "Low").sum() / len(df) * 100
print(f"Low_percent: {low_percent.round(2)} %")

ram_catagory_means = df.groupby('RAM_GB')['Price'].mean()
ram_8_mean_of_price = ram_catagory_means.get(8)
ram_16_mean_of_price = ram_catagory_means.get(16)
ram_32_mean_of_price = ram_catagory_means.get(32)

print(f"ram_8_mean_of_price: {ram_8_mean_of_price.round(2)}")
print(f"ram_16_mean_of_price: {ram_16_mean_of_price.round(2)}")
print(f"ram_32_mean_of_price: {ram_32_mean_of_price.round(2)}")

ssd_catagory_means = df.groupby('SSD_GB')['Price'].mean()
ssd_256_mean_of_price = ssd_catagory_means.get(256)
ssd_512_mean_of_price = ssd_catagory_means.get(512)
ssd_1024_mean_of_price = ssd_catagory_means.get(1024)

print(f"ssd_256_mean_of_price: {ssd_256_mean_of_price.round(2)}")
print(f"ssd_512_mean_of_price: {ssd_512_mean_of_price.round(2)}")
print(f"ssd_1024_mean_of_price: {ssd_1024_mean_of_price.round(2)}")

sns.set_theme(style="darkgrid", rc={"figure.figsize":(7, 5)})
sns.set_palette("husl")
sns.scatterplot(data=df, x=df["Price"], y=df["RAM_GB"], hue=df["SSD_GB"], palette="husl")
plt.show()

mean_of_price_brand = df.groupby("Brand")[["Price", "RAM_GB", "SSD_GB"]].mean()
print(mean_of_price_brand.round(2))

ram_8_percent = (df["RAM_GB"] == 8).sum() / len(df) * 100
print(f"ram_8_percent: {ram_8_percent.round(2)} %")
ram_16_percent = (df["RAM_GB"] == 16).sum() / len(df) * 100
print(f"ram_16_percent: {ram_16_percent.round(2)} %")
ram_32_percent = (df["RAM_GB"] == 32).sum() / len(df) * 100
print(f"ram_32_percent: {ram_32_percent.round(2)} %")
ssd_256_percent = (df["SSD_GB"] == 256).sum() / len(df) * 100
print(f"ssd_256_percent: {ssd_256_percent.round(2)} %")
ssd_512_percent = (df["SSD_GB"] == 512).sum() / len(df) * 100
print(f"ssd_512_percent: {ssd_512_percent.round(2)} %")
ssd_1024_percent = (df["SSD_GB"] == 1024).sum() / len(df) * 100
print(f"ssd_1024_percent: {ssd_1024_percent.round(2)} %")

values = [ram_8_percent, ram_16_percent, ram_32_percent]
labels = ["RAM 8", "RAM 16", "RAM 32"]
color = ["#4E79A7", "#F28E2B", "#59A14F"]
plt.pie(values, labels=labels, colors = color)
plt.show()

value = [ssd_256_percent, ssd_512_percent, ssd_1024_percent]
labels = ["SSD 256", "SSD 512", "SSD 1024"]
color = ["#1F78B4", "#33A02C", "#B2DF8A"]
plt.pie(value, labels=labels, colors = color)
plt.show()

most_expensive = df.nlargest(5, "Price")
print(most_expensive[["Brand", "Price", "RAM_GB", "SSD_GB"]])
cheapest = df.nsmallest(5, "Price")
print(cheapest[["Brand", "Price", "RAM_GB", "SSD_GB"]])

avg_price_by_config = df.groupby(["RAM_GB", "SSD_GB"])["Price"].mean().round(2)
avg_price_by_config = avg_price_by_config.reset_index()
avg_price_by_config = avg_price_by_config.sort_values(by="Price", ascending=False)
print(avg_price_by_config.head(5))

mean_of_price_ram = df.groupby("RAM_GB")["Price"].mean().round(2)
mean_of_price_ram = mean_of_price_ram.reset_index()
mean_of_price_ram = mean_of_price_ram.sort_values(by="Price", ascending=False)
print(mean_of_price_ram.head(5))
mean_of_price_ssd = df.groupby("SSD_GB")["Price"].mean().round(2)
mean_of_price_ssd = mean_of_price_ssd.reset_index()
mean_of_price_ssd = mean_of_price_ssd.sort_values(by="Price", ascending=False)
print(mean_of_price_ssd.head(5))

"""## Conclusion

After cleaning and preprocessing the laptop dataset collected from Newegg,
hardware features such as RAM and SSD were extracted and standardized for analysis.

The analysis of average prices by hardware configuration shows clear differences
across various RAM and SSD combinations. Results indicate that laptops with higher
RAM capacities generally have higher average prices. While increasing SSD capacity
also leads to higher prices, its impact appears to be less pronounced compared to RAM.

Overall, this project demonstrates how basic exploratory data analysis can reveal
meaningful pricing patterns based on hardware specifications.

## نتیجه‌گیری

پس از پاکسازی و آماده‌سازی داده‌های لپ‌تاپ جمع‌آوری‌شده از سایت Newegg،
اطلاعات مربوط به رم و حافظه SSD استخراج و به قالب عددی استاندارد تبدیل شد.

تحلیل میانگین قیمت بر اساس ترکیب‌های مختلف رم و SSD نشان داد که قیمت لپ‌تاپ‌ها
با افزایش مقدار رم به‌طور قابل‌توجهی افزایش می‌یابد. اگرچه افزایش ظرفیت SSD نیز
باعث افزایش قیمت می‌شود، اما تأثیر آن نسبت به رم کمتر است.

این پروژه نشان می‌دهد که با استفاده از تحلیل اکتشافی داده‌ها می‌توان الگوهای
قیمتی معناداری را بر اساس مشخصات سخت‌افزاری شناسایی کرد.
"""